Iter15
OlegVankov/verbose-umbrella pull request #12
Opened 2023-07-31 18:24 UTC by OlegVankov

2023-08-04 06:12 UTC, valentinsoe commented on internal/handler/updates.go
> +func (h *Handler) checkHash(next http.Handler) http.Handler {
Кажется не самый удачный файл для этой функции. Это все-таки скорее middleware

2023-08-04 06:18 UTC, valentinsoe requested changes
Спасибо за работу. Извини, что долго проверял.
Замерджи пожалуйста прошлый PR(iter13), чтобы количество изменений было поменьше.
Такая организация параллельной отправки явно не противоречит заданию, но поведение ее будет не очень предсказуемым.
И функция отправки в таком случае не должна делать return (это надо исправить)

2023-08-04 06:18 UTC, valentinsoe commented on internal/monitor/sender.go
> +					return
По мере возниковения проблем(выключить сервер на достаточное время) - все горутины выйдут и процесс агента завершится. Что не совсем правильно.

2023-08-10 13:17 UTC, OlegVankov commented on internal/handler/updates.go
> +func (h *Handler) checkHash(next http.Handler) http.Handler {
commit: 8451408fa34691be16310041710c784226ab8c59
перенес в middleware

2023-08-10 13:18 UTC, OlegVankov commented on internal/monitor/sender.go
> +					return
commit: d83625153e00df08e67f13065050d0eeab34af56
усыпил горутину на время с продолжением работы

2023-08-10 19:15 UTC, valentinsoe approved these changes
Спасибо за исправления. Работу принимаю

2024-03-11 16:55 UTC, merged