Iter9
OlegVankov/verbose-umbrella pull request #9
Opened 2023-06-30 13:29 UTC by OlegVankov

2023-07-03 06:58 UTC, valentinsoe requested changes
Спасибо за работу.
Все весьма аккуратно написано.

Из глобальных замечаний - настрой пожалуйста все-таки goimports, чтобы он автоматически сортировал импорты. А то в разных файлах по-разному.
Игнорировать ошибки(записи в файл, сериализации json) не хорошо. Они кажется сейчас не могут возникнуть. Но если дописывать код в будущем и ошибки появяться, то отлавливать их будет сложно.
gzip ответа сервера должен зависеть от заголовков ответа сервера, а не запроса клиента. Это точно нужно исправить(что не совсем тривиально). Если не получится - приходи с вопросами.
И сохранение/восстановление хранилища кажется не должно быть в пакете обработки запросов:)

В остальном - супер.

2023-07-03 06:58 UTC, valentinsoe commented on cmd/agent/main.go
>  	mtr "github.com/OlegVankov/verbose-umbrella/internal/monitor"
Alias для пакетов - не очень удачное решение. Без лишней нужды его лучше не применять.
Можно переменную назвать mtr :)

2023-07-03 06:58 UTC, valentinsoe commented on cmd/server/flags.go
> +	flag.StringVar(&serverAddr, "a", "127.0.0.1:8080", "адрес и порт сервера")
В задании значение по умолчанию как раз localhost:8080.
Это в некоторых случаях не то же самое, что 127.0.0.1

2023-07-03 06:58 UTC, valentinsoe commented on cmd/server/main.go
> +	"context"
Лучше порядок импортов форматировать используя goimports

2023-07-03 06:58 UTC, valentinsoe commented on cmd/server/main.go
> +		if err := handler.RestoreStorage(fileStoragePath); err != nil {
RestoreStorage/SaveStorage не обработчики http запросов. Кажется их лучше отнести в пакет хранилища.

2023-07-03 06:58 UTC, valentinsoe commented on internal/handler/handler.go
> +			_, _ = file.Write(data)
Лучше обработать ошибку и написать о ней в лог, чем просто проигнорировать.
И запись 1 метрики в файл можно выделить в функцию, чтобы не дублировать код.

2023-07-03 06:58 UTC, valentinsoe commented on internal/handler/home.go
> +		w.WriteHeader(http.StatusBadGateway)
Кажется не самый удачный код ответа:) StatusInternalServerError подойдет лучше

2023-07-03 06:58 UTC, valentinsoe commented on internal/handler/middleware.go
> +	"github.com/OlegVankov/verbose-umbrella/internal/logger"
Хорошо, что ты самостоятельно реализовал middleware.
Но в chi есть готовая middleware - compress.

2023-07-03 06:58 UTC, valentinsoe commented on internal/handler/middleware.go
> +		if strings.Contains(contentEncoding, "gzip") {
Дурацкое занудство. Но я бы сначала написал код отвечающий за чтение запроса, а потом код отвечающий за кодирование результата.

2023-07-03 06:58 UTC, valentinsoe commented on internal/handler/middleware.go
> +	rw http.ResponseWriter
Лучше бы было кажется встроить оригинальный ResponseWriter.
Тогда функции Header и WriteHeader можно было бы не менять.

2023-07-03 06:58 UTC, valentinsoe commented on internal/monitor/monitor.go
> +		data, _ := json.Marshal(&metric)
Лучше не игнорировать такие ошибки, даже если они кажутся маловероятными.
Однажды кто-то где-нибудь поменяет структуру и будет совершенно непонятно, почему data окажется не тем, что ожидается.

2023-07-03 06:58 UTC, valentinsoe commented on internal/monitor/monitor.go
> +		var buf bytes.Buffer
Часть про gzip я бы убрал в отдельную функцию, чтобы эту не перегружать.

2023-07-03 06:58 UTC, valentinsoe commented on internal/handler/middleware.go
> +			(strings.Contains(contentType, "application/json") || strings.Contains(contentType, "text/html") || strings.Contains(accept, "html/text")) {
Вот эта проверка не корректна.
contentType мы взяли из запроса клиента. И в зависимости от него делаем gzip или не делаем.
А надо использовать contentType ответа сервера. Если не получится придумать, как это сделать - пиши, обсудим.

2023-07-03 21:22 UTC, OlegVankov commented on internal/handler/middleware.go
> +			(strings.Contains(contentType, "application/json") || strings.Contains(contentType, "text/html") || strings.Contains(accept, "html/text")) {
убрал проверку) но пока не разобрался как сделать так чтобы можно было проверить Content-Type у responseWriter который возращается после обработки  хендлером(

2023-07-04 04:04 UTC, valentinsoe requested changes
Ответил на вопрос касательно заголовков.
И все еще игнорируются ошибки во множестве мест.

2023-07-04 04:04 UTC, valentinsoe commented on cmd/server/main.go
> +	hdl "github.com/OlegVankov/verbose-umbrella/internal/handler"
Тут аналогично с monitor. Придумывать алиасы пакетам - это средство ссудного дня, когда у тебя например в импорте два пакета с одинаковыми именами:)

2023-07-04 04:04 UTC, valentinsoe commented on internal/handler/middleware.go
> +			(strings.Contains(contentType, "application/json") || strings.Contains(contentType, "text/html") || strings.Contains(accept, "html/text")) {
Логика проверки Content-Type должна быть в методе Write твоей реализации ResponseWriter.
В зависимости от заголовка ты можешь либо писать в оригинальный io.Writer, либо в "гзипующий" io.Writer.

2023-07-04 04:04 UTC, valentinsoe commented on internal/handler/middleware.go
> +	return g.gw.Write(bytes)
Вот в этом методе надо проверять заголовки.

2023-07-04 18:33 UTC, valentinsoe approved these changes
Спасибо за исправления.
Я там еще немного позанудстововал в комментариях, но исправлять их не принципиально.
Работу принимаю.

2023-07-04 18:33 UTC, valentinsoe commented on cmd/agent/flags.go
> +	"go.uber.org/zap"
Пожалуйста, настрой goimports:)
"go.uber.org/zap" должен быть между "strconv" и внутренним пакетом логгера

2023-07-04 18:33 UTC, valentinsoe commented on cmd/server/main.go
> +	c := make(chan os.Signal, 1)
Мы пока работу с сигналами не проходили, но хорошо, что ты уже их использовал для корректного завершения приложения.

2023-07-04 18:33 UTC, valentinsoe commented on internal/handler/middleware.go
> +		contentEncoding := strings.Join(r.Header.Values("Content-Encoding"), ",")
Еще немного занудства.
Если вдруг клиент пришлет несколько заголовков Content-Encoding, как выбрать алгоритм который применять к телу запроса?
Тут лучше явное сравнение, что Content-Encoding(единственный) строго равен gzip, а не содержит его.

2023-07-04 18:33 UTC, valentinsoe commented on internal/handler/update.go
> +	//w.WriteHeader(http.StatusOK)
Лучше не оставлять куски кода в комментариях, если они не особо ценны для истории:)

2023-07-06 07:23 UTC, merged